### ISSUE TITLE
ERROR: The system was unable to find the specified registry key or value.

### ISSUE THREAD

**Issue by GeraShrek** [renpy/pygame_sdl2#116]

**Comment by GeraShrek** [comment]
C:\Users\tyske\rapt>python android.py installsdk
ERROR: The system was unable to find the specified registry key or value.
ERROR: The system was unable to find the specified registry key or value.
Traceback (most recent call last):
  File "android.py", line 14, in <module>
    import rapt.build as build
  File "buildlib\rapt\build.py", line 22, in <module>
    import jinja2
  File "C:\Users\tyske\rapt\buildlib\jinja2.egg\jinja2\__init__.py", line 37, in <module>
    from jinja2.environment import Environment, Template
  File "C:\Users\tyske\rapt\buildlib\jinja2.egg\jinja2\environment.py", line 552
    info.external_attr = 0755 << 16L
                            ^
SyntaxError: invalid token

**Comment by GeraShrek** [comment]
C:\Users\tyske\rapt>python android.py installsdk
Found b'C:\\Program Files\\Java\\jdk1.8.0_191'
Traceback (most recent call last):
  File "buildlib\rapt\plat.py", line 105, in <module>
    set_win32_java_home()
  File "buildlib\rapt\plat.py", line 85, in set_win32_java_home
    os.environ["JAVA_HOME"] = keys[jh]
  File "C:\Users\tyske\AppData\Local\Programs\Python\Python36-32\lib\os.py", line 674, in __setitem__
    value = self.encodevalue(value)
  File "C:\Users\tyske\AppData\Local\Programs\Python\Python36-32\lib\os.py", line 730, in check_str
    raise TypeError("str expected, not %s" % type(value).__name__)
TypeError: str expected, not bytes
I'm compiling a short test program, to see if you have a working JDK
on your system.
Traceback (most recent call last):
  File "android.py", line 69, in <module>
    main()
  File "android.py", line 42, in main
    install_sdk.install_sdk(iface)
  File "buildlib\rapt\install_sdk.py", line 234, in install_sdk
    check_java(interface)
  File "buildlib\rapt\install_sdk.py", line 47, in check_java
    if not run_slow(interface, plat.javac, plat.path("buildlib/CheckJDK8.java"), use_path=True):
  File "buildlib\rapt\install_sdk.py", line 35, in run_slow
    interface.call(args, cancel=True, **kwargs)
  File "buildlib\rapt\interface.py", line 238, in call
    subprocess.check_call(args, cwd=plat.RAPT_PATH)
AttributeError: module 'plat' has no attribute 'RAPT_PATH'
