### ISSUE TITLE
Blitting doesn't support vector object

### ISSUE THREAD

**Issue by runedevros** [renpy/pygame_sdl2#19]
I'm trying to get my project [Story of a Lost Sky](http://www.bitbucket.org/featheredmelody/lost-sky-project-public) running on Pygame_SDL2. I rely heavily on a Vector2 package for vector math called [GameObjects](https://pypi.python.org/pypi/gameobjects/0.0.3) and while I can directly pass it as a blitting coordinate in Pygame it looks like Pygame_SDL2 doesn't support this.

```
2016-01-15 21:01:23.274 Python[4243:25701] 21:01:23.274 WARNING:  140: This application, or a library it uses, is using the deprecated Carbon Component Manager for hosting Audio Units. Support for this will be removed in a future release. Also, this makes the host incompatible with version 3 audio units. Please transition to the API's in AudioComponent.h.
Traceback (most recent call last):
  File "/Users/rune_devros/Documents/lostskyproject/sandbox/vector2_test.py", line 185, in <module>
    main()
  File "/Users/rune_devros/Documents/lostskyproject/sandbox/vector2_test.py", line 178, in main
    screen.blit(block, coord)
  File "src/pygame_sdl2/surface.pyx", line 184, in pygame_sdl2.surface.Surface.blit (gen/pygame_sdl2.surface.c:2832)
  File "src/pygame_sdl2/rect.pyx", line 379, in pygame_sdl2.rect.to_sdl_rect (gen/pygame_sdl2.rect.c:10458)
TypeError: Argument dest must be a rect style object.

```

Rather than trying the entire SoaLS codebase, I've included a snippet of code that demonstrates this behavior. The following code works with Pygame (if you comment out the first two lines), but not Pygame_SDL2

```python
# Comment out these two lines to go back to old Pygame version
import pygame_sdl2
pygame_sdl2.import_as_pygame()

import pygame
from pygame import KEYDOWN, QUIT
import sys

# Vector 2 class:
# Modified Minimal Implementation from GameObjects
# https://pypi.python.org/pypi/gameobjects/0.0.3

from math import sqrt

class Vector2(object):

    __slots__ = ('_v', )

    _gameobjects_vector = 2


    def __init__(self, x=0., y=0.):
        """Initialise a vector

        @type x: number
        @param x: The x value (defaults to 0.), or a container of 2 values
        @type x: number
        @param y: The y value (defaults to 0.)

        """
        if hasattr(x, "__getitem__"):
            x, y = x
            self._v = [float(x), float(y)]
        else:
            self._v = [float(x), float(y)]

    def _get_length(self):
        x, y = self._v
        return sqrt(x*x + y*y)
    def _set_length(self, length):
        v = self._v
        try:
            x, y = v
            l = length / sqrt(x*x +y*y)
        except ZeroDivisionError:
            v[0] = 0.0
            v[1] = 0.0
            return self
        v[0] *= l
        v[1] *= l
    length = property(_get_length, _set_length, None, "Length of the vector")


    @classmethod
    def from_floats(cls, x, y):
        vec = cls.__new__(cls, object)
        vec._v = [x, y]
        return vec


    def __iter__(self):

        return iter(self._v[:])

    def __len__(self):

        return 2


    def __getitem__(self, index):
        """Gets a component as though the vector were a list."""
        try:
            return self._v[index]
        except IndexError:
            raise IndexError, "There are 2 values in this object, index should be 0 or 1"


    def __add__(self, rhs):
        x, y = self._v
        xx, yy = rhs
        return Vector2.from_floats(x+xx, y+yy)




def main():

    pygame.init()
    tilesize = 35
    size_x = 24
    size_y = 18
    screen_size = (tilesize * size_x, tilesize * size_y)
    screen = pygame.display.set_mode(screen_size, 0, 32)
    clock = pygame.time.Clock()

    stop_flag = False

    coord = Vector2(50,50)

    block = pygame.Surface((30,30))
    block.fill((255,0,0))


    while not stop_flag:

        for event in pygame.event.get():
            if event.type == KEYDOWN or event.type == QUIT:
                sys.exit()


        screen.fill((200,200,200))

        # Passing a Vector object to blit doesn't work in Pygame SDL2 but works in Pygame
        screen.blit(block, coord)

        screen.blit(block, coord+(50,50))

        pygame.display.flip()
        clock.tick(60)


if __name__ == '__main__':
    main()
```

**Comment by renpytom** [comment]
Thank you for sending in truly good bug reports that make it easy to track down and fix bugs. I wish every report was this detailed, and I apologize for taking so long to fix the problem.

**Comment by runedevros** [comment]
No problem! I'm glad that I could help out because I'm very interested in moving our project to a more modern library. I'll be reporting to you things that break and since SoaLS is a fairly big project we have a lot of stuff that can immediately show me where things in your library and Pygame don't line up. Thanks again for your hard work on this project.

**Comment by renpytom** [comment]
It's good to see a project like yours wanting to move to pygame_sdl2. A problem with pygame_sdl2 development is that with Ren'Py being the main project to use it, it's been hard to shake out the bugs in the areas Ren'Py doesn't use. Having another big project using pygame_sdl2 will help with that. 

Feel free to keep sending bug reports, or - for problems you feel comfortable handling - pull requests.
