### ISSUE TITLE
sdl2 setup,py install

### ISSUE THREAD

**Issue by Burgess168** [renpy/pygame_sdl2#51]
Hi, I follow instruction to install sdl2, but have files can't be found issue. Did I miss something? The python is 2.7.11 in windows 10. Below is the message from system. Thanks.

C:\pygame_sdl2-2.1.0a2016.06.04>python setup.py install
Traceback (most recent call last):
  File "setup.py", line 47, in <module>
    parse_cflags([ "sh", "-c", "sdl2-config --cflags" ])
  File "C:\pygame_sdl2-2.1.0a2016.06.04\setuplib.py", line 93, in parse_cflags
    output = subprocess.check_output(command, universal_newlines=True)
  File "C:\Python27\lib\subprocess.py", line 566, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "C:\Python27\lib\subprocess.py", line 710, in __init__
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 958, in _execute_child
    startupinfo)
WindowsError: [Error 2]

**Comment by renpytom** [comment]
Yes, it looks like you don't have the windows dependencies present.

**Comment by Burgess168** [comment]
Thanks. It should not have this kind of thing, because it always updating by itself. I never have this experience. I will try to figure out what's happened on windows 10 and update again if there is correct answer.
BTW, if back to windows 7 with pygame_sdl2, is it better than Win10 now or do you have any advice if this issue can't be solved?

**Comment by okbalefthanded** [comment]
I'm in the same situation, I had clone the pygame_sdl2_windeps repo in the same parent folder where I previously cloned the pygame_sdl2 repo, when I run the setup command: 
python setup.py install
I got the similar windowsError : [Error2] the system cannont find the file specified

**Comment by okbalefthanded** [comment]
I figured out how to install the lib by using the nightly build source.

**Comment by python346** [comment]
Hi I'm also having this problem and I have tried using the nightly build but that hasn't worked either. Could someone please explain what I should do to resolve this?
