### ISSUE TITLE
setup on win7 x86-64 python 3.5 x86

### ISSUE THREAD

**Issue by LukeMS** [renpy/pygame_sdl2#54]
`python.exe setup.py install:`

> Traceback (most recent call last):
>   File "setup.py", line 47, in <module>
>     parse_cflags([ "sh", "-c", "sdl2-config --cflags" ])
>   File "C:\pygame_sdl2\setuplib.py", line 93, in parse_cflags
>     output = subprocess.check_output(command, universal_newlines=True)
>   File "c:\Python35-32\lib\subprocess.py", line 629, in check_output
>     **kwargs).stdout
>   File "c:\Python35-32\lib\subprocess.py", line 696, in run
>     with Popen(*popenargs, **kwargs) as process:
>   File "c:\Python35-32\lib\subprocess.py", line 950, in __init__
>     restore_signals, start_new_session)
>   File "c:\Python35-32\lib\subprocess.py", line 1220, in _execute_child
>     startupinfo)
> FileNotFoundError: [WinError 2] O sistema n\xe3o pode encontrar o arquivo especificado
> (=The system couldn't find the specified file)

**Comment by LukeMS** [comment]
my mistake, "pygame_sdl2_windeps" was named as "pygame_sdl2_windeps-master" in the install folder.
