### ISSUE TITLE
pygame_sdl2.error is out of date

### ISSUE THREAD

**Issue by shivamshekhar** [renpy/pygame_sdl2#62]
I get the following error while running python setup.py install

```
shivam@shivam-Inspiron-3542 ~/Documents/My Projects/Python/pygame/pygame_sdl2-master $ python setup.py install
pygame_sdl2.error is out of date.
Traceback (most recent call last):
  File "setup.py", line 109, in <module>
    cython("pygame_sdl2.error", libs=sdl_libs)
  File "/home/shivam/Documents/My Projects/Python/pygame/pygame_sdl2-master/setuplib.py", line 245, in cython
    c_fn])
  File "/usr/lib/python2.7/subprocess.py", line 536, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 523, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

```
I am running Linux Mint 18 "Serena" Cinnamon edition

**Comment by shivamshekhar** [comment]
Also, i get the following while running `python fix_virtualenv.py`

```
shivam@shivam-Inspiron-3542 ~/Documents/My Projects/Python/pygame/pygame_sdl2-master $ python fix_virtualenv.py
/usr/include/python2.7 is not a symlink. Perhaps this script has already been run.
```

**Comment by shivamshekhar** [comment]
Ok. Thanks man! That did the job. At first I didn't knew I had to separately install cython (basically, I didn't even knew what cython was. I am still a noob. Sigh!).
